---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator
  namespace: orders
  labels:
    app: generator
spec:
  selector:
    matchLabels:
      app: generator
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: generator
    spec:
      containers:
        - image: buoyantio/slow_cooker:latest
          name: default
          env:
            - name: QPS
              value: "50"
            - name: CONCURRENCY
              value: "5"
            - name: SERVICE
              value: fulfillment
            - name: PORT
              value: "80"
            - name: ITERATIONS
              value: "30"
          command: ["/bin/sh", "-c"]
          args:
            - |-
              sed -e "s/\${SERVICE}/$SERVICE/" -e "s/\${PORT}/$PORT/" /tmp/urls | slow_cooker/slow_cooker -qps ${QPS} -concurrency ${CONCURRENCY} -iterations ${ITERATIONS} @-
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
          securityContext:
            runAsUser: 1337
          volumeMounts:
            - name: cfg
              mountPath: /tmp/
      volumes:
        - name: cfg
          configMap:
            name: generator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: generator
  namespace: orders
data:
  urls: |-
    http://${SERVICE}:${PORT}
    http://${SERVICE}:${PORT}/healthz
    http://${SERVICE}:${PORT}/readyz
    http://${SERVICE}:${PORT}/configs
    http://${SERVICE}:${PORT}/env
    http://${SERVICE}:${PORT}/headers
