# hazl-orders-playground-k3d-small.yaml
# Cluster configuration using k3d for the hazl-orders-playground GitHub repository
# https://github.com/BuoyantIO/hazl-orders-playground
# Tom Dean | Buoyant
# Last edit: 3/6/2025
#
# k3d configuration docs:
# https://k3d.io/v5.6.3/usage/configfile/

apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: hazl-orders-playground
servers: 3
agents: 3
network: hazl-orders-playground
image: rancher/k3s:v1.32.2-rc3-k3s1-arm64
options:
  k3d:
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --debug
        nodeFilters:
          - server:*
          - agent:*
      - arg: --disable=traefik
        nodeFilters: [server:*]
    nodeLabels:
      - label: topology.kubernetes.io/zone=zone-central
        nodeFilters: [agent:0]
      - label: topology.kubernetes.io/zone=zone-west
        nodeFilters: [agent:1]
      - label: topology.kubernetes.io/zone=zone-east
        nodeFilters: [agent:2]
      - label: egressgateway=true
        nodeFilters: [agent:*]
