---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-east
  namespace: orders
  labels:
    app: orders
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: oha
        image: hatoo/oha:latest
        imagePullPolicy: Never
        args: ["-q", "10", "-z", "525600m", "http://fulfillment.orders.svc.cluster.local"]
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 1000m
            memory: 100Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values: [zone-east]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-east-config
  namespace: orders
  labels:
    app: orders
data:
  config.yml: |
    requestsPerSecond: 50
    reportIntervalSeconds: 10
    uri: http://fulfillment.orders.svc.cluster.local
