---
apiVersion: v1
kind: Service
metadata:
  name: fulfillment
  namespace: orders
  annotations:
    balancer.linkerd.io/failure-accrual: consecutive
  labels:
    mirror.linkerd.io/exported: remote-discovery
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: fulfillment
