---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-oakland
  namespace: orders
  labels:
    color: warehouse-oakland
    app: fulfillment
spec:
  replicas: 3
  selector:
    matchLabels:
      color: warehouse-oakland
      app: fulfillment
  template:
    metadata:
      labels:
        color: warehouse-oakland
        app: fulfillment
      annotations:
        config.linkerd.io/proxy-cpu-request: "0.5"
    spec:
      containers:
      - name: bb
        image: docker.io/buoyantio/bb:v0.0.7
        ports:
        - containerPort: 8080
        args: ["terminus", "--h1-server-port", "8080", "--sleep-in-millis", "200", "--response-text", "success"]
        resources:
          requests:
            cpu: 10m # Overprovision
            memory: 10Mi
          limits:
            cpu: 1000m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values: [zone-west]
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: warehouse-oakland
  namespace: orders
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: warehouse-oakland
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 25
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 90