# hazl-orders-playground-kind-large.yaml
# Cluster configuration using KIND for the hazl-orders-playground GitHub repository
# https://github.com/BuoyantIO/hazl-orders-playground
# Tom Dean | Buoyant
# Last edit: 6/10/2024
#
# KIND configuration docs:
# https://kind.sigs.k8s.io/docs/user/configuration/

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cni-test-cluster
nodes:
- role: control-plane
  image: kindest/node:v1.30.0
- role: control-plane
  image: kindest/node:v1.30.0
- role: control-plane
  image: kindest/node:v1.30.0
- role: worker
  image: kindest/node:v1.30.0
- role: worker
  image: kindest/node:v1.30.0
- role: worker
  image: kindest/node:v1.30.0