apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: hazl-orders-playground
servers: 1
agents: 3
network: hazl-orders-playground
ports:
  - port: 9999:80 # same as `--port '9999:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
image: rancher/k3s:v1.30.1-k3s1
options:
  k3d:
    disableLoadbalancer: false
  k3s:
    extraArgs:
      - arg: --debug
        nodeFilters: [server:*]
    nodeLabels:
      - label: topology.kubernetes.io/zone=zone-central
        nodeFilters: [agent:0]
      - label: topology.kubernetes.io/zone=zone-west
        nodeFilters: [agent:1]
      - label: topology.kubernetes.io/zone=zone-east
        nodeFilters: [agent:2]
