apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: hazl-orders-playground
servers: 1
agents: 3
network: multiaz-orders-hazl
ports:
  - port: 9999:80 # same as `--port '9999:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
image: rancher/k3s:v1.29.2-k3s1
volumes:
  - volume: "./calico.yaml:/var/lib/rancher/k3s/server/manifests/calico.yaml"
    nodeFilters:
      - server:0
      - agent:*
options:
  k3d:
    disableLoadbalancer: false
  k3s:
    extraArgs:
      - arg: --debug
        nodeFilters: [server:*]
      - arg: --flannel-backend=none@server:*
        nodeFilters: [server:*]
    nodeLabels:
      - label: topology.kubernetes.io/zone=zone-central
        nodeFilters: [agent:0]
      - label: topology.kubernetes.io/zone=zone-west
        nodeFilters: [agent:1]
      - label: topology.kubernetes.io/zone=zone-east
        nodeFilters: [agent:2]
