{
 "title": "HAZL Dashboard",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "client_deployment",
    "label": "Client Deployment(s)",
    "query": {
     "query": "label_values(response_total,deployment)"
    }
   },
   {
    "name": "client_namespace",
    "label": "Client Namespace(s)",
    "query": {
     "query": "label_values(response_total,namespace)"
    }
   },
   {
    "name": "application_deployment",
    "label": "Application Deployment(s)",
    "query": {
     "query": "label_values(response_total,deployment)"
    }
   },
   {
    "name": "application_namespace",
    "label": "Application Namespace(s)",
    "query": {
     "query": "label_values(response_total,namespace)"
    }
   },
   { "name": "traffic_cost", "label": "Traffic Cost", "query": "0.02,0.03,0.04,0.05" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://buoyant.cloud/dist/favicon.ico\" style=\"height:32px;\"/>&nbsp;\n  <span style=\"font-size: 32px\">High-Availability Zonal Load Balancing (HAZL) Dashboard</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum (\n  sum(\n    rate(\n      tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n    +\n    rate(\n      tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n  ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n  * on (pod) group_left (topology_kubernetes_io_zone)\n  (\n    sum(\n      container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n    ) by (pod, topology_kubernetes_io_zone)\n    * 0 + 1\n  )\n  unless ignoring(matching_zone)\n  (\n    label_replace(\n      sum(\n        rate(\n          tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"topology_kubernetes_io_zone\",\n      \"(.*)\"\n    )\n    ==\n    label_replace(\n      sum(\n        rate(\n          tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"dst_zone\",\n      \"(.*)\"\n    )\n  )\n)",
     "legendFormat": "Cross-AZ"
    },
    {
     "expr": "sum (\n  sum(\n    rate(\n      tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n    +\n    rate(\n      tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n  ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n  * on (pod) group_left (topology_kubernetes_io_zone)\n  (\n    sum(\n      container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n    ) by (pod, topology_kubernetes_io_zone)\n    * 0 + 1\n  )\n  and ignoring(matching_zone)\n  (\n    label_replace(\n      sum(\n        rate(\n          tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"topology_kubernetes_io_zone\",\n      \"(.*)\"\n    )\n    ==\n    label_replace(\n      sum(\n        rate(\n          tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"dst_zone\",\n      \"(.*)\"\n    )\n  )\n)",
     "legendFormat": "Same-AZ"
    }
   ]
  },
  {
   "title": "Cross-AZ Yearly Traffic Cost ($)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  sum(\n    rate(\n      tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n    +\n    rate(\n      tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n  ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n  * on (pod) group_left (topology_kubernetes_io_zone)\n  (\n    sum(\n      container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n    ) by (pod, topology_kubernetes_io_zone)\n    * 0 + 1\n  )\n  unless ignoring(matching_zone)\n  (\n    label_replace(\n      sum(\n        rate(\n          tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"topology_kubernetes_io_zone\",\n      \"(.*)\"\n    )\n    ==\n    label_replace(\n      sum(\n        rate(\n          tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"dst_zone\",\n      \"(.*)\"\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate: Orders By Zone",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(response_total{direction=\"outbound\", classification=\"success\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\"}[1m])) by (deployment)\n/\nsum(rate(response_total{direction=\"outbound\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\"}[1m])) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cross-AZ Traffic (GB/s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  sum(\n    rate(\n      tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n    +\n    rate(\n      tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n  ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n  * on (pod) group_left (topology_kubernetes_io_zone)\n  (\n    sum(\n      container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n    ) by (pod, topology_kubernetes_io_zone)\n    * 0 + 1\n  )\n  unless ignoring(matching_zone)\n  (\n    label_replace(\n      sum(\n        rate(\n          tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"topology_kubernetes_io_zone\",\n      \"(.*)\"\n    )\n    ==\n    label_replace(\n      sum(\n        rate(\n          tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"dst_zone\",\n      \"(.*)\"\n    )\n  )\n)",
     "legendFormat": "{{Cross-AZ Traffic (GB)}}"
    }
   ]
  },
  {
   "title": "Latency: Orders By Zone (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n    histogram_quantile(\n        0.95,\n        sum(\n            rate(\n                response_latency_ms_bucket{direction=\"outbound\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\"}[1m]\n            )\n        ) by (\n            le,namespace,deployment\n        )\n    )\n) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Requests: All Orders",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(response_total{direction=\"outbound\", no_tls_reason!=\"loopback\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\"}[1m]))",
     "legendFormat": "Overall Requests"
    }
   ]
  },
  {
   "title": "Requests: Orders By Zone",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(response_total{direction=\"outbound\", no_tls_reason!=\"loopback\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\"}[1m])) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Same-AZ Traffic: By Destination",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum (\n  sum(\n    rate(\n      tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n    +\n    rate(\n      tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n  ) by (namespace, deployment, pod, instance, dst_namespace, dst_deployment, dst_pod, dst_zone)\n  * on (pod) group_left (topology_kubernetes_io_zone)\n  (\n    sum(\n      container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n    ) by (pod, topology_kubernetes_io_zone)\n    * 0 + 1\n  )\n  and ignoring(matching_zone)\n  (\n    label_replace(\n      sum(\n        rate(\n          tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, deployment, pod, instance, dst_namespace, dst_deployment, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"topology_kubernetes_io_zone\",\n      \"(.*)\"\n    )\n    ==\n    label_replace(\n      sum(\n        rate(\n          tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n         tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, deployment, pod, instance, dst_namespace, dst_deployment, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"dst_zone\",\n      \"(.*)\"\n    )\n  )\n) by (dst_namespace, dst_deployment)",
     "legendFormat": "{{dst_deployment}}"
    }
   ]
  },
  {
   "title": "Cross-AZ Traffic: By Destination",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum (\n  sum(\n    rate(\n      tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n    +\n    rate(\n      tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n  ) by (namespace, deployment, pod, instance, dst_namespace, dst_deployment, dst_pod, dst_zone)\n  * on (pod) group_left (topology_kubernetes_io_zone)\n  (\n    sum(\n      container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n    ) by (pod, topology_kubernetes_io_zone)\n    * 0 + 1\n  )\n  unless ignoring(matching_zone)\n  (\n    label_replace(\n      sum(\n        rate(\n          tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, deployment, pod, instance, dst_namespace, dst_deployment, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"topology_kubernetes_io_zone\",\n      \"(.*)\"\n    )\n    ==\n    label_replace(\n      sum(\n        rate(\n          tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment=~\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, deployment, pod, instance, dst_namespace, dst_deployment, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"dst_zone\",\n      \"(.*)\"\n    )\n  )\n) by (dst_namespace, dst_deployment)",
     "legendFormat": "{{dst_deployment}}"
    }
   ]
  },
  {
   "title": "Overall Requests: All Warehouses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(response_total{direction=\"inbound\", no_tls_reason!=\"loopback\", namespace=~\"$application_namespace\", deployment=~\"$application_deployment\"}[1m]))",
     "legendFormat": "Overall Requests"
    }
   ]
  },
  {
   "title": "Requests By Warehouse",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(response_total{direction=\"inbound\", no_tls_reason!=\"loopback\", namespace=~\"$application_namespace\", deployment=~\"$application_deployment\"}[1m])) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cross-AZ traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment!=\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n    }[1m]\n  )\n  +\n  rate(\n    tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment!=\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n    }[1m]\n  )\n) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n* on (pod) group_left (topology_kubernetes_io_zone)\n(\n  sum(\n    container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n  ) by (pod, topology_kubernetes_io_zone)\n  * 0 + 1\n)\nunless ignoring(matching_zone)\n(\n  label_replace(\n    sum(\n      rate(\n        tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment!=\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n        }[1m]\n      )\n      +\n      rate(\n       tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment!=\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n        }[1m]\n      )\n    ) by (namespace, del, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n    * on (pod) group_left (topology_kubernetes_io_zone)\n    (\n      sum(\n        container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n      ) by (pod, topology_kubernetes_io_zone)\n      * 0 + 1\n    ),\n    \"matching_zone\",\n    \"$1\",\n    \"topology_kubernetes_io_zone\",\n    \"(.*)\"\n  )\n  ==\n  label_replace(\n    sum(\n    rate(\n        tcp_write_bytes_total{direction=\"outbound\", namespace=~\"$client_namespace\", deployment!=\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n        }[1m]\n      )\n      +\n      rate(\n        tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment!=\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n        }[1m]\n      )\n    ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n    * on (pod) group_left (topology_kubernetes_io_zone)\n    (\n      sum(\n        container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n      ) by (pod, topology_kubernetes_io_zone)\n      * 0 + 1\n    ),\n    \"matching_zone\",\n    \"$1\",\n    \"dst_zone\",\n    \"(.*)\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Same-AZ traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment!=\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n    }[1m]\n  )\n  +\n  rate(\n    tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment!=\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n    }[1m]\n  )\n) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n* on (pod) group_left (topology_kubernetes_io_zone)\n(\n  sum(\n    container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n  ) by (pod, topology_kubernetes_io_zone)\n  * 0 + 1\n)\nand ignoring(matching_zone)\n(\n  label_replace(\n    sum(\n      rate(\n        tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment!=\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n        }[1m]\n      )\n      +\n      rate(\n        tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment!=\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n        }[1m]\n      )\n    ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n    * on (pod) group_left (topology_kubernetes_io_zone)\n    (\n      sum(\n        container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n      ) by (pod, topology_kubernetes_io_zone)\n      * 0 + 1\n    ),\n    \"matching_zone\",\n    \"$1\",\n    \"topology_kubernetes_io_zone\",\n    \"(.*)\"\n  )\n  ==\n  label_replace(\n    sum(\n      rate(\n        tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment!=\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n        }[1m]\n      )\n      +\n      rate(\n        tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment!=\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n        }[1m]\n      )\n    ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n    * on (pod) group_left (topology_kubernetes_io_zone)\n    (\n      sum(\n        container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n      ) by (pod, topology_kubernetes_io_zone)\n      * 0 + 1\n    ),\n    \"matching_zone\",\n    \"$1\",\n    \"dst_zone\",\n    \"(.*)\"\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raw outbound reads + writes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "  rate(\n    tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment!=\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n    }[1m]\n  )\n  +\n  rate(\n    tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$client_namespace\", deployment!=\"$client_deployment\", peer=\"dst\", dst_zone!=\"\"\n    }[1m]\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Meshed Pods by Zone",
   "type": "table",
   "gridPos": { "h": 17, "w": 5, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"linkerd-proxy\"}) by (pod, topology_kubernetes_io_zone)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 75 },
   "options": {
    "content": "<div>\n  <div style=\"position: absolute; top: 0, left: 0\">\n    <a href=\"https://buoyant.cloud\" target=\"_blank\"><img src=\"https://buoyant.io/images/buoyant_logo.svg\" style=\"height: 30px;\"></a>\n  </div>\n</div>\n"
   },
   "targets": [
    {}
   ]
  }
 ]
}