{
 "title": "HAZL | Orders Dashboard",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(response_total,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://buoyant.cloud/dist/favicon.ico\" style=\"height:32px;\"/>&nbsp;\n  <span style=\"font-size: 32px\">$cluster_name</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum (\n  sum(\n    rate(\n      tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n    +\n    rate(\n      tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n  ) by (namespace, workload_name, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n  * on (pod) group_left (topology_kubernetes_io_zone)\n  (\n    sum(\n      container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n    ) by (pod, topology_kubernetes_io_zone)\n    * 0 + 1\n  )\n  unless ignoring(matching_zone)\n  (\n    label_replace(\n      sum(\n        rate(\n          tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, workload_name, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"topology_kubernetes_io_zone\",\n      \"(.*)\"\n    )\n    ==\n    label_replace(\n      sum(\n        rate(\n          tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, workload_name, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"dst_zone\",\n      \"(.*)\"\n    )\n  )\n)",
     "legendFormat": "Cross-AZ"
    },
    {
     "expr": "sum (\n  sum(\n    rate(\n      tcp_write_bytes_total{direction=\"outbound\", cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n    +\n    rate(\n      tcp_read_bytes_total{direction=\"outbound\", cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n  ) by (namespace, workload_name, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n  * on (pod) group_left (topology_kubernetes_io_zone)\n  (\n    sum(\n      container_memory_working_set_bytes{cluster_name=\"$cluster_name\", container=\"linkerd-proxy\"}\n    ) by (pod, topology_kubernetes_io_zone)\n    * 0 + 1\n  )\n  and ignoring(matching_zone)\n  (\n    label_replace(\n      sum(\n        rate(\n          tcp_write_bytes_total{direction=\"outbound\", cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          tcp_read_bytes_total{direction=\"outbound\", cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, workload_name, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{cluster_name=\"$cluster_name\", container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"topology_kubernetes_io_zone\",\n      \"(.*)\"\n    )\n    ==\n    label_replace(\n      sum(\n        rate(\n          tcp_write_bytes_total{direction=\"outbound\", cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          tcp_read_bytes_total{direction=\"outbound\", cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, workload_name, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{cluster_name=\"$cluster_name\", container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"dst_zone\",\n      \"(.*)\"\n    )\n  )\n)",
     "legendFormat": "Same-AZ"
    }
   ]
  },
  {
   "title": "Success Rate: Orders By Zone",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(response_total{direction=\"outbound\", classification=\"success\", deployment=~\"orders-.*\"}[1m])) by (deployment)\n/\nsum(rate(response_total{direction=\"outbound\", deployment=~\"orders-.*\"}[1m])) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency: Orders By Zone (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n    histogram_quantile(\n        0.95,\n        sum(\n            rate(\n                response_latency_ms_bucket{direction=\"outbound\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", workload_kind=~\"$workload_kind\", workload_name=~\"orders-.*\"}[1m]\n            )\n        ) by (\n            le,cluster_id,cluster_name,\n            namespace,workload_kind,workload_name\n        )\n    )\n) by (workload_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Requests: All Warehouses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(workload:inbound_response:rate1m{cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", workload_kind=~\"$workload_kind\", workload_name=~\"warehouse-.*\"})",
     "legendFormat": "Overall Requests"
    }
   ]
  },
  {
   "title": "Requests By Warehouse",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(workload:inbound_response:rate1m{cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", workload_kind=~\"$workload_kind\", workload_name=~\"warehouse-.*\"}) by (workload_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Same-AZ Traffic: By Destination",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum (\n  sum(\n    rate(\n      outbound_tcp_write_bytes_total{\n        cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n    +\n    rate(\n      outbound_tcp_read_bytes_total{\n        cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n  ) by (namespace, workload_name, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n  * on (pod) group_left (topology_kubernetes_io_zone)\n  (\n    sum(\n      container_memory_working_set_bytes{cluster_name=\"$cluster_name\", container=\"linkerd-proxy\"}\n    ) by (pod, topology_kubernetes_io_zone)\n    * 0 + 1\n  )\n  and ignoring(matching_zone)\n  (\n    label_replace(\n      sum(\n        rate(\n          outbound_tcp_write_bytes_total{\n            cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          outbound_tcp_read_bytes_total{\n            cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, workload_name, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{cluster_name=\"$cluster_name\", container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"topology_kubernetes_io_zone\",\n      \"(.*)\"\n    )\n    ==\n    label_replace(\n      sum(\n        rate(\n          outbound_tcp_write_bytes_total{\n            cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          outbound_tcp_read_bytes_total{\n            cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, workload_name, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{cluster_name=\"$cluster_name\", container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"dst_zone\",\n      \"(.*)\"\n    )\n  )\n) by (dst_namespace, dst_workload_name)",
     "legendFormat": "{{dst_workload_name}}"
    }
   ]
  },
  {
   "title": "Cross-AZ Traffic: By Destination",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum (\n  sum(\n    rate(\n      outbound_tcp_write_bytes_total{\n        cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n    +\n    rate(\n      outbound_tcp_read_bytes_total{\n        cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n      }[1m]\n    )\n  ) by (namespace, workload_name, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n  * on (pod) group_left (topology_kubernetes_io_zone)\n  (\n    sum(\n      container_memory_working_set_bytes{cluster_name=\"$cluster_name\", container=\"linkerd-proxy\"}\n    ) by (pod, topology_kubernetes_io_zone)\n    * 0 + 1\n  )\n  unless ignoring(matching_zone)\n  (\n    label_replace(\n      sum(\n        rate(\n          outbound_tcp_write_bytes_total{\n            cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          outbound_tcp_read_bytes_total{\n            cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, workload_name, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{cluster_name=\"$cluster_name\", container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"topology_kubernetes_io_zone\",\n      \"(.*)\"\n    )\n    ==\n    label_replace(\n      sum(\n        rate(\n          outbound_tcp_write_bytes_total{\n            cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n        +\n        rate(\n          outbound_tcp_read_bytes_total{\n            cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n          }[1m]\n        )\n      ) by (namespace, workload_name, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n      * on (pod) group_left (topology_kubernetes_io_zone)\n      (\n        sum(\n          container_memory_working_set_bytes{cluster_name=\"$cluster_name\", container=\"linkerd-proxy\"}\n        ) by (pod, topology_kubernetes_io_zone)\n        * 0 + 1\n      ),\n      \"matching_zone\",\n      \"$1\",\n      \"dst_zone\",\n      \"(.*)\"\n    )\n  )\n) by (dst_namespace, dst_workload_name)",
     "legendFormat": "{{dst_workload_name}}"
    }
   ]
  },
  {
   "title": "Overall Requests: All Orders",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(workload:outbound_response:rate1m{cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", workload_kind=~\"$workload_kind\", workload_name=~\"orders-.*\"})",
     "legendFormat": "Overall Requests"
    }
   ]
  },
  {
   "title": "Requests: Orders By Zone",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(workload:outbound_response:rate1m{cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", workload_kind=~\"$workload_kind\", workload_name=~\"orders-.*\"}) by (workload_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    tcp_write_bytes_total{direction=\"outbound\", cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n    }[1m]\n  )\n  +\n  rate(\n    tcp_read_bytes_total{direction=\"outbound\", cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n    }[1m]\n  )\n) by (namespace, workload_name, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n* on (pod) group_left (topology_kubernetes_io_zone)\n(\n  sum(\n    container_memory_working_set_bytes{cluster_name=\"$cluster_name\", container=\"linkerd-proxy\"}\n  ) by (pod, topology_kubernetes_io_zone)\n  * 0 + 1\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Same-AZ traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", deployment!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n    }[1m]\n  )\n  +\n  rate(\n    tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", deployment!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n    }[1m]\n  )\n) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n* on (pod) group_left (topology_kubernetes_io_zone)\n(\n  sum(\n    container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n  ) by (pod, topology_kubernetes_io_zone)\n  * 0 + 1\n)\nand ignoring(matching_zone)\n(\n  label_replace(\n    sum(\n      rate(\n        tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", deployment!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n        }[1m]\n      )\n      +\n      rate(\n        tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", deployment!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n        }[1m]\n      )\n    ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n    * on (pod) group_left (topology_kubernetes_io_zone)\n    (\n      sum(\n        container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n      ) by (pod, topology_kubernetes_io_zone)\n      * 0 + 1\n    ),\n    \"matching_zone\",\n    \"$1\",\n    \"topology_kubernetes_io_zone\",\n    \"(.*)\"\n  )\n  ==\n  label_replace(\n    sum(\n      rate(\n        tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", deployment!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n        }[1m]\n      )\n      +\n      rate(\n        tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", deployment!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n        }[1m]\n      )\n    ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n    * on (pod) group_left (topology_kubernetes_io_zone)\n    (\n      sum(\n        container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n      ) by (pod, topology_kubernetes_io_zone)\n      * 0 + 1\n    ),\n    \"matching_zone\",\n    \"$1\",\n    \"dst_zone\",\n    \"(.*)\"\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cross-AZ traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", deployment!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n    }[1m]\n  )\n  +\n  rate(\n    tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", deployment!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n    }[1m]\n  )\n) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n* on (pod) group_left (topology_kubernetes_io_zone)\n(\n  sum(\n    container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n  ) by (pod, topology_kubernetes_io_zone)\n  * 0 + 1\n)\nunless ignoring(matching_zone)\n(\n  label_replace(\n    sum(\n      rate(\n        tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", deployment!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n        }[1m]\n      )\n      +\n      rate(\n       tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", deployment!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n        }[1m]\n      )\n    ) by (namespace, del, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n    * on (pod) group_left (topology_kubernetes_io_zone)\n    (\n      sum(\n        container_memory_working_set_bytes{cluster_name=\"$cluster_name\", container=\"linkerd-proxy\"}\n      ) by (pod, topology_kubernetes_io_zone)\n      * 0 + 1\n    ),\n    \"matching_zone\",\n    \"$1\",\n    \"topology_kubernetes_io_zone\",\n    \"(.*)\"\n  )\n  ==\n  label_replace(\n    sum(\n    rate(\n        tcp_write_bytes_total{direction=\"outbound\", cluster_name=\"$cluster_name\", tls=\"true\", namespace=~\"$namespace\", workload_name!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n        }[1m]\n      )\n      +\n      rate(\n        tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", deployment!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n        }[1m]\n      )\n    ) by (namespace, deployment, pod, instance, dst_namespace, dst_workload_name, dst_pod, dst_zone)\n    * on (pod) group_left (topology_kubernetes_io_zone)\n    (\n      sum(\n        container_memory_working_set_bytes{container=\"linkerd-proxy\"}\n      ) by (pod, topology_kubernetes_io_zone)\n      * 0 + 1\n    ),\n    \"matching_zone\",\n    \"$1\",\n    \"dst_zone\",\n    \"(.*)\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raw outbound reads + writes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "  rate(\n    tcp_write_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", deployment!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n    }[1m]\n  )\n  +\n  rate(\n    tcp_read_bytes_total{direction=\"outbound\", tls=\"true\", namespace=~\"$namespace\", deployment!=\"buoyant-cloud-metrics\",peer=\"dst\", dst_zone!=\"\"\n    }[1m]\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods : Zones",
   "type": "table",
   "gridPos": { "h": 17, "w": 5, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"linkerd-proxy\"}) by (pod, topology_kubernetes_io_zone)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 82 },
   "options": {
    "content": "<div>\n  <div style=\"position: absolute; top: 0, left: 0\">\n    <a href=\"https://buoyant.cloud\" target=\"_blank\"><img src=\"https://buoyant.io/images/buoyant_logo.svg\" style=\"height: 30px;\"></a>\n  </div>\n</div>\n"
   },
   "targets": [
    {}
   ]
  }
 ]
}